import nodemailer from 'nodemailer';
import type { InsertContactMessage } from '@shared/schema';

/**
 * Sends a professional contact email using Nodemailer.
 * 
 * @param data - The contact form data (name, email, phone, message)
 */
export async function sendContactEmail(data: InsertContactMessage): Promise<void> {
  const emailUser = process.env.EMAIL_USER;
  const emailPass = process.env.EMAIL_PASS;
  const recipientEmail = process.env.RECIPIENT_EMAIL || emailUser;

  // Validate environment variables
  if (!emailUser || !emailPass) {
    console.error('[Email] Missing EMAIL_USER or EMAIL_PASS environment variables.');
    throw new Error('Email service is not configured.');
  }

  // Create transporter (configured for Gmail by default)
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: emailUser,
      pass: emailPass,
    },
  });

  const mailOptions = {
    from: `"Tower Top Contact Form" <${emailUser}>`,
    to: recipientEmail,
    replyTo: data.email,
    subject: data.subject ? `[Contact Form] ${data.subject}` : `New Contact Message: From ${data.name}`,
    text: `
      You have received a new message from your website contact form.

      --- Contact Details ---
      Name: ${data.name}
      Email: ${data.email}
      Phone: ${data.phone}
      Subject: ${data.subject}

      --- Message ---
      ${data.message}

      -----------------------
      This email was automatically generated by the Tower Top Backend.
    `,
    html: `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #eee; padding: 20px; border-radius: 10px;">
        <h2 style="color: #d32f2f; border-bottom: 2px solid #d32f2f; padding-bottom: 10px;">New Contact Message</h2>
        <p>You have received a new message from the <strong>Tower Top</strong> contact form.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold; background: #f9f9f9; width: 30%;">Name</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.name}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold; background: #f9f9f9;">Email</td>
            <td style="padding: 10px; border: 1px solid #eee;"><a href="mailto:${data.email}">${data.email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold; background: #f9f9f9;">Phone</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.phone || 'Not provided'}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #eee; font-weight: bold; background: #f9f9f9;">Subject</td>
            <td style="padding: 10px; border: 1px solid #eee;">${data.subject || 'Not provided'}</td>
          </tr>
        </table>
        
        <div style="margin-top: 30px;">
          <h3 style="color: #555;">Message Content:</h3>
          <div style="padding: 15px; background: #f4f4f4; border-radius: 5px; white-space: pre-wrap;">${data.message}</div>
        </div>
        
        <footer style="margin-top: 30px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #eee; pt-10px;">
          <p>Sent from Tower Top Backend System</p>
        </footer>
      </div>
    `,
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`[Email] Successfully sent message from ${data.email} to ${recipientEmail}`);
  } catch (error) {
    console.error('[Email] Failed to send email:', error);
    throw new Error('Failed to deliver email. Please try again later.');
  }
}
